### PR TITLE
fix(mrc): dont render TileBlock optional label

### LINKED ISSUE #15260: [manager-components]: <TileBlock /> label should not render if empty
### On which entity, you would like to report a bug?

TileBlock

### Description

Due to recent changes, right now the `TileBlock` label props is optional but it still renders if it is empty (at least on Firefox)

### Steps to reproduce

Declare a `<DashboardTile />` with some `items` without a `label` property

Image

We want to be able to not render the `label` element if it is empty

Image

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tristanwagner**
ref: ISSUE-15260

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop` 
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #15260  
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] Only FR translations have been updated
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] Breaking change is mentioned in relevant commits

### CODE REVIEW

**Review by tibs245 — DISMISSED** [review]

**Review by ghyenne — DISMISSED** [review]

File: packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx [hunk 1]
```diff
@@ -11,9 +11,11 @@ export const TileBlock: React.FC<React.PropsWithChildren<TileBlockProps>> = ({
...
-    <dt>
-      <OdsText preset={ODS_TEXT_PRESET.heading6}>{label}</OdsText>
-    </dt>
+    {label && (
+      <dt>
+        <OdsText preset={ODS_TEXT_PRESET.heading6}>{label}</OdsText>
+      </dt>
+    )}
     <dd className="m-0">{children}</dd>
   </dl>
```
Comment (anooparveti) [inline packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx:20]: **nitpick:** By definition, `dd` tag provides the description for the preciding term `dt`.
If you have a requirement to not display `dt`, then imo, we have to think of adding modes for this where you display datalist/text/link.

**Review by anooparveti — CHANGES_REQUESTED** [review]

File: packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx [hunk 2]
```diff
@@ -11,9 +11,11 @@ export const TileBlock: React.FC<React.PropsWithChildren<TileBlockProps>> = ({
   children,
 }) => (
   <dl className="flex flex-col gap-1 m-0">
-    <dt>
-      <OdsText preset={ODS_TEXT_PRESET.heading6}>{label}</OdsText>
-    </dt>
+    {label && (
```
Comment (SimonChaumet) [inline packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx:14]:
```suggestion
    {!!label && (
```
If label is a string it will display both

Comment (tristanwagner) [reply packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx]: I agree it's better that the boolean check is explicit, however I'm pretty sure it won't have this behavior you describe. Anyway I updated it !

File: packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx (hunk 1 above)
Comment (tristanwagner) [reply packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx]: I updated as we said earlier, keeping the `dt` anyway but not rendering the `OdsText` since it is the part that cause the unwanted space

Comment (rjamet-ovh) [reply packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx]: For actions items, it will be better to not use dl/dt/dd, and render something specific. (probably a div with margin children)

**Review by anooparveti — APPROVED** [review]

**Review by aboungnaseng-ovhcloud — APPROVED** [review]
