### PR TITLE
fix(mrc): fix <OnboardingLayout />

### LINKED ISSUE #14934: [manager-components]: <OnboardingLayout />
### On which entity, you would like to report a bug?

`<OnboardingLayout />`

### Description

Update to fix the onboarding layout
- more info: use a button instead of a link
- spacing: update to match design specs

### Steps to reproduce

/

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by rjamet-ovh**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #14934
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

- more info: use `<OdsButton />`
- update css to match design specs

### CODE REVIEW

**Review by chipp972 — DISMISSED** [review]

File: packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx [hunk 1]
```diff
@@ -72,34 +92,28 @@ export const OnboardingLayout: React.FC<OnboardingLayoutProps> = ({
...
-                width={img?.width}
-                height={img?.height}
+                alt={altText ?? 'placeholder image'}
               />
             </div>
           )}
           <OdsText
             preset={ODS_TEXT_PRESET.heading1}
-            className="block text-center sm:pt-8 xs:pt-2.5"
+            className="block text-center "
```
Comment (darsene) [inline packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx:112]: **Niptick** 
```suggestion
            className="block text-center"
```

**Review by aboungnaseng-ovhcloud — DISMISSED** [review]

**Review by darsene — APPROVED** [review]

File: packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx [hunk 2]
```diff
@@ -72,34 +92,28 @@ export const OnboardingLayout: React.FC<OnboardingLayoutProps> = ({
...
+            className="block text-center"
           >
             {title}
           </OdsText>
-          {description && (
-            <OdsText preset="span" className="onboarding-description">
-              {description}
-            </OdsText>
-          )}
+          {description}
```
Comment (anooparveti) [inline packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx:116]: **nitpick:** I think this can have adverse effect on existing apps if they dont pass `description` inside an `OdsText`.
IMO, `OdsText` must be retained.

**Review by anooparveti — CHANGES_REQUESTED** [review]

File: packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx (hunk 2 above)
Comment (rjamet-ovh) [reply packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx:116]: Since it has been decided to allow free composition on the description part of the layout ( `description?: React.ReactNode;`), it makes no sense to keep an `<OdsText />` as a wrapper :

```
<OdsText>
  <div>
    <OdsText>...</OdsText>
     <OdsText>...</OdsText>
  </div>
</OdsText>
```

It a small adjustment, and some app may have to fix their implementation, but it better match the template interface.

**Review by aboungnaseng-ovhcloud — APPROVED** [review]

File: packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx (hunk 2 above)
Comment (tristanwagner) [reply packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx:116]: It is a breaking change for Zimbra, so please mention it to trigger the version bump, thamk you !

Comment (rjamet-ovh) [reply packages/manager-react-components/src/components/templates/onboarding/onboarding.component.tsx:116]: breaking change mentioned in commit.
