### PR TITLE
fix(telephony): get all events related to current month

### LINKED ISSUE #4362: telephony: event scheduler does not retreive events beginning ou ending outside specified timeframe
**Describe the bug**
Called URL is like: 	https://www.ovhtelecom.fr/engine/apiv6/telephony/xxxxxxxx/scheduler/xxxxx/events?dateEnd.to=2021-02-01&dateStart.from=2020-12-28

My event scheduled from 2021-01-29 to 2021-02-08 is not retrieved, and so not displayed in the UI.

Should make 2 requests, one with dateEnd.to=2021-02-01, the other with dateStart.from=2020-12-28, and merge results with unique filter.

### PR DESCRIPTION
**Pull request by JeremyDec**
DTRSD-6859
Signed-off-by: JeremyDec <jeremy.de-cesare@ovhcloud.com>

| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes
| New feature?     | no
| Breaking change? | no
| Tickets          | Fix #DTRSD-6859
| License          | BSD 3-Clause

## Description

resolves #4362 

cc @julieni

### CODE REVIEW

File: packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js [hunk 1]
```diff
@@ -70,8 +70,13 @@ export default /* @ngInject */ function TelephonySchedulerCtrl(
 
     return self.scheduler
       .getEvents({
-        'dateStart.from': start.format(),
-        'dateEnd.to': end.format(),
+        'dateStart.from': moment(start)
+          .subtract(1, 'm')
```
Comment (frenautvh) [inline packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: why would you subtract 1 month from start ?

Comment (JeremyDec) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: In order to get the previous month, as an event which start on n-1 of current month won't be retrieve by api

Comment (frenautvh) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: for example if you have an event last month from the 1st to the 3rd it will be returned but it does not belong in the [start, end] interval (it is in the [start-1M, start] interval
is it an issue or is it simply not displayed in the front ?

Comment (JeremyDec) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: Yes it is an issue:
- An event which starts on last month (so event.dateStart < start) , but ends the current month (event.endDate > start), won't be displayed.

Same logic with the end: if event.dateStart < end + event.dateEnd > end, it won't be displayed.
So here I'm increasing the range to get those kind of events, so they will be displayed.

**Review by frenautvh — APPROVED** [review]

File: packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js (hunk 1 above)
Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: I think 2 request should be made and results merge with uniqueness, because some events may be set for weeks, even months (lockdown is coming guys...)

Comment (JeremyDec) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: In fact @julieni, two requests as you suggest won't be enough.
If we set an event which last for 6 months, (starting on 2020-12-01, ending on 2021-05-01), it won't be catched.

The solution is that API allows rule as is:
- someEvent.dateStart <= request.dateStart <= someEvent.dateEnd.

Or to increase range from start of last year, to end of current year (with a little possibility to not catch event with larger time range).

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: @JeremyDec, I think it will, and even 1 request should be enough, as I rechecked parameters of https://api.ovh.com/console/#/telephony/%7BbillingAccount%7D/scheduler/%7BserviceName%7D/events#GET

- dateEnd.from = first day of the period we want to display
- dateStart.to = last day of the period we want to display

In other words, for period d1 to d2: dateEnd >= d1 && dateStart <= d2

Seems to work, but I just woke up ;)

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: Just tested:
- dateEnd.from = 2021-02-01 and dateStart.to = 2021-02-28 shows my event from 2021-01-29 to 2021-02-07
- dateEnd.from = 2020-12-28 and dateStart.to = 2021-01-31 shows my event from 2021-01-29 to 2021-02-07 too

File: packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js [hunk 2]
```diff
@@ -70,8 +70,12 @@ export default /* @ngInject */ function TelephonySchedulerCtrl(
 
     return self.scheduler
       .getEvents({
-        'dateStart.from': start.format(),
-        'dateEnd.to': end.format(),
+        'dateStart.to': moment(start)
```
Comment (julieni) [inline packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:73]: I think you switched dateStart.to and dateEnd.from values

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:73]: dateEnd.from should be 1st day of period, while dateStart.to should be last day of period

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:73]: and it's not the start and the end of the month
I think the original code is OK, just switch values between dateStart.from and dateEnd.to

File: packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js [hunk 3]
```diff
@@ -70,8 +70,12 @@ export default /* @ngInject */ function TelephonySchedulerCtrl(
 
     return self.scheduler
       .getEvents({
-        'dateStart.from': start.format(),
-        'dateEnd.to': end.format(),
+        'dateStart.to': moment(end)
+          .startOf('month')
```
Comment (julieni) [inline packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: why ```startOf('month')```?

if should just be:
```
'dateStart.to': end.format(),
'dateEnd.from': start.format()
```
no ?

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: what works:
- dateEnd.from = 2021-02-01 and dateStart.to = 2021-02-28 shows my event from 2021-01-29 to 2021-02-07
- dateEnd.from = 2020-12-28 and dateStart.to = 2021-01-31 shows my event from 2021-01-29 to 2021-02-07 too

Comment (JeremyDec) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js:74]: @julieni yes the `startOf()` was a remnant of previous code, it is removed.
Now with these parameters, you should be able to retrieve either:

- Events starting before and finishing after current month.
- All events which overlap start/end of the month
- classic ones

Comment (julieni) [reply packages/manager/apps/telecom/src/components/telecom/telephony/scheduler/scheduler.controller.js]: yep last commit seems OK to me :+1:

**Review by antleblanc — APPROVED** [review]
