### PR TITLE
fix(mrc): fix <TileBlock />

### LINKED ISSUE #14917: [manager-components]: <TileBlock />
### On which entity, you would like to report a bug?

TileBlock

### Description

  - fix layout css
  - use `<OdsText />` for label
  - simplify children part to be more flexible and handle all content use-cases (composition like data + action, clipboard etc...)

### Steps to reproduce

/

### Browser

_No response_

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by rjamet-ovh**
| Question         | Answer
| ---------------- | ---
| Branch?          | `develop`
| Bug fix?         | yes/no
| New feature?     | yes/no
| Breaking change? | yes/no
| Tickets          | Fix #14917
| License          | BSD 3-Clause

- [x] Try to keep pull requests small so they can be easily reviewed.
- [x] Commits are signed-off
- [ ] ~~Only FR translations have been updated~~
- [x] Branch is up-to-date with target branch
- [x] Lint has passed locally
- [x] Standalone app was ran and tested locally
- [x] Ticket reference is mentioned in linked commits (internal only)
- [ ] ~~Breaking change is mentioned in relevant commits~~

## Description

- fix layout
- use <OdsText /> for label

### CODE REVIEW

**Review by chipp972 — DISMISSED** [review]

**Review by pauldkn — DISMISSED** [review]

**Review by tibs245 — APPROVED** [review]

File: packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx [hunk 1]
```diff
@@ -8,12 +10,8 @@ export const TileBlock: React.FC<React.PropsWithChildren<TileBlockProps>> = ({
...
-      {label}
-    </dt>
-    <dd className="tile-block-description m-0 text-[--ods-color-text] text-[16px] leading-[16px] min-h-[16px]">
-      {children}
-    </dd>
-  </dl>
+  <div className="flex flex-col gap-1">
+    <OdsText preset={ODS_TEXT_PRESET.heading6}>{label}</OdsText>
+    {children}
+  </div>
```
Comment (anooparveti) [inline packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx:16]: **nitpick:** Retaining the `dl dt dd` format is good imo as it provides the necessary accessibility https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl and in fact it's ties the label to the information.

**Review by anooparveti — CHANGES_REQUESTED** [review]

File: packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx (hunk 1 above)
Comment (rjamet-ovh) [reply packages/manager-react-components/src/components/content/dashboard-tile/tile-block.component.tsx]: fixed

**Review by anooparveti — APPROVED** [review]

**Review by tibs245 — APPROVED** [review]

**Review by pauldkn — APPROVED** [review]
